In [1]:
%pip install numpy pandas matplotlib seaborn

Collecting numpy
  Using cached numpy-2.4.6-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Collecting pandas
  Using cached pandas-3.0.3-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting matplotlib
  Downloading matplotlib-3.11.0-cp314-cp314-win_amd64.whl.metadata (80 kB)
Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.63.0-cp314-cp314-win_amd64.whl.metadata (121 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in .\.venv\lib\site-packages (from matplotlib) (26.2)
Collecting pillow>=9 (from matplotlib)
  Using cached pillow-12.2.0-cp314-cp314-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: six>=1.5 in .\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached numpy-2.4.6-cp314-cp314-win_amd64.whl (12.5 MB)
Using cached pandas-3.0.3-cp314-cp314-win_amd64.whl (9.9 MB)
Downloading matplotlib-3.11.0-cp314-cp314-win_amd64.whl (9.5 MB)
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.5 MB 396.6 kB/s eta 0:00:23
   -- ------------------------------------- 0.5/9.5 MB 396.6 kB/s eta 0:00:23
   -- ------------------------------------- 0.5/9.5 MB 396.6 kB/s eta 0:00:23
   --- ------------------------------------ 0.8/9.5 MB 430.2 kB/s eta 0:00:21
   --- ------------------------------------ 0.8/9.5 MB 430.2 kB/s eta 0:00:21
   --- ------------------------------------ 0.8/9.5 MB 430.2 kB/s eta 0:00:21
   ---- ----------------------------------- 1.0/9.5 MB 407.1 kB/s eta 0:00:21
   ---- ----------------------------------- 1.0/9.5 MB 407.1 kB/s eta 0:00:21
   ---- ----------------------------------- 1.0/9.5 MB 407.1 kB/s eta 0:00:21
   ---- ----------------------------------- 1.0/9.5 MB 407.1 kB/s eta 0:00:21
   ----- ---------------------------------- 1.3/9.5 MB 392.8 kB/s eta 0:00:21
   ----- ---------------------------------- 1.3/9.5 MB 392.8 kB/s eta 0:00:21
   ----- ---------------------------------- 1.3/9.5 MB 392.8 kB/s eta 0:00:21
   ----- ---------------------------------- 1.3/9.5 MB 392.8 kB/s eta 0:00:21
   ------ --------------------------------- 1.6/9.5 MB 366.5 kB/s eta 0:00:22
   ------ --------------------------------- 1.6/9.5 MB 366.5 kB/s eta 0:00:22
   ------ --------------------------------- 1.6/9.5 MB 366.5 kB/s eta 0:00:22
   ------- -------------------------------- 1.8/9.5 MB 373.7 kB/s eta 0:00:21
   ------- -------------------------------- 1.8/9.5 MB 373.7 kB/s eta 0:00:21
   ------- -------------------------------- 1.8/9.5 MB 373.7 kB/s eta 0:00:21
   -------- ------------------------------- 2.1/9.5 MB 379.4 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.5 MB 379.4 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.5 MB 379.4 kB/s eta 0:00:20
   --------- ------------------------------ 2.4/9.5 MB 376.0 kB/s eta 0:00:19
   --------- ------------------------------ 2.4/9.5 MB 376.0 kB/s eta 0:00:19
   --------- ------------------------------ 2.4/9.5 MB 376.0 kB/s eta 0:00:19
   ----------- ---------------------------- 2.6/9.5 MB 377.5 kB/s eta 0:00:19
   ----------- ---------------------------- 2.6/9.5 MB 377.5 kB/s eta 0:00:19
   ----------- ---------------------------- 2.6/9.5 MB 377.5 kB/s eta 0:00:19
   ----------- ---------------------------- 2.6/9.5 MB 377.5 kB/s eta 0:00:19
   ----------- ---------------------------- 2.6/9.5 MB 377.5 kB/s eta 0:00:19
   ------------ --------------------------- 2.9/9.5 MB 365.6 kB/s eta 0:00:19
   ------------ --------------------------- 2.9/9.5 MB 365.6 kB/s eta 0:00:19
   ------------ --------------------------- 2.9/9.5 MB 365.6 kB/s eta 0:00:19
   ------------ --------------------------- 2.9/9.5 MB 365.6 kB/s eta 0:00:19
   ------------ --------------------------- 2.9/9.5 MB 365.6 kB/s eta 0:00:19
   ------------- -------------------------- 3.1/9.5 MB 346.3 kB/s eta 0:00:19
   ------------- -------------------------- 3.1/9.5 MB 346.3 kB/s eta 0:00:19
   -------------- ------------------------- 3.4/9.5 MB 356.8 kB/s eta 0:00:18
   -------------- ------------------------- 3.4/9.5 MB 356.8 kB/s eta 0:00:18
   -------------- ------------------------- 3.4/9.5 MB 356.8 kB/s eta 0:00:18
   -------------- ------------------------- 3.4/9.5 MB 356.8 kB/s eta 0:00:18
   --------------- ------------------------ 3.7/9.5 MB 357.6 kB/s eta 0:00:17
   --------------- ------------------------ 3.7/9.5 MB 357.6 kB/s eta 0:00:17
   --------------- ------------------------ 3.7/9.5 MB 357.6 kB/s eta 0:00:17
   ---------------- ----------------------- 3.9/9.5 MB 358.0 kB/s eta 0:00:16
   ---------------- ----------------------- 3.9/9.5 MB 358.0 kB/s eta 0:00:16
   ---------------- ----------------------- 3.9/9.5 MB 358.0 kB/s eta 0:00:16
   ----------------- ---------------------- 4.2/9.5 MB 358.4 kB/s eta 0:00:15
   ----------------- ---------------------- 4.2/9.5 MB 358.4 kB/s eta 0:00:15
   ----------------- ---------------------- 4.2/9.5 MB 358.4 kB/s eta 0:00:15
   ----------------- ---------------------- 4.2/9.5 MB 358.4 kB/s eta 0:00:15
   ------------------ --------------------- 4.5/9.5 MB 358.8 kB/s eta 0:00:15
   ------------------ --------------------- 4.5/9.5 MB 358.8 kB/s eta 0:00:15
   ------------------ --------------------- 4.5/9.5 MB 358.8 kB/s eta 0:00:15
   ------------------ --------------------- 4.5/9.5 MB 358.8 kB/s eta 0:00:15
   ------------------ --------------------- 4.5/9.5 MB 358.8 kB/s eta 0:00:15
   ------------------- -------------------- 4.7/9.5 MB 351.1 kB/s eta 0:00:14
   ------------------- -------------------- 4.7/9.5 MB 351.1 kB/s eta 0:00:14
   --------------------- ------------------ 5.0/9.5 MB 356.0 kB/s eta 0:00:13
   --------------------- ------------------ 5.0/9.5 MB 356.0 kB/s eta 0:00:13
   --------------------- ------------------ 5.0/9.5 MB 356.0 kB/s eta 0:00:13
   ---------------------- ----------------- 5.2/9.5 MB 358.3 kB/s eta 0:00:12
   ---------------------- ----------------- 5.2/9.5 MB 358.3 kB/s eta 0:00:12
   ---------------------- ----------------- 5.2/9.5 MB 358.3 kB/s eta 0:00:12
   ---------------------- ----------------- 5.2/9.5 MB 358.3 kB/s eta 0:00:12
   ----------------------- ---------------- 5.5/9.5 MB 358.0 kB/s eta 0:00:12
   ----------------------- ---------------- 5.5/9.5 MB 358.0 kB/s eta 0:00:12
   ----------------------- ---------------- 5.5/9.5 MB 358.0 kB/s eta 0:00:12
   ------------------------ --------------- 5.8/9.5 MB 359.1 kB/s eta 0:00:11
   ------------------------ --------------- 5.8/9.5 MB 359.1 kB/s eta 0:00:11
   ------------------------ --------------- 5.8/9.5 MB 359.1 kB/s eta 0:00:11
   ------------------------- -------------- 6.0/9.5 MB 359.3 kB/s eta 0:00:10
   ------------------------- -------------- 6.0/9.5 MB 359.3 kB/s eta 0:00:10
   ------------------------- -------------- 6.0/9.5 MB 359.3 kB/s eta 0:00:10
   -------------------------- ------------- 6.3/9.5 MB 359.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.3/9.5 MB 359.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.3/9.5 MB 359.8 kB/s eta 0:00:09
   -------------------------- ------------- 6.3/9.5 MB 359.8 kB/s eta 0:00:09
   --------------------------- ------------ 6.6/9.5 MB 360.2 kB/s eta 0:00:09
   --------------------------- ------------ 6.6/9.5 MB 360.2 kB/s eta 0:00:09
   --------------------------- ------------ 6.6/9.5 MB 360.2 kB/s eta 0:00:09
   --------------------------- ------------ 6.6/9.5 MB 360.2 kB/s eta 0:00:09
   ---------------------------- ----------- 6.8/9.5 MB 358.9 kB/s eta 0:00:08
   ---------------------------- ----------- 6.8/9.5 MB 358.9 kB/s eta 0:00:08
   ----------------------------- ---------- 7.1/9.5 MB 360.8 kB/s eta 0:00:07
   ----------------------------- ---------- 7.1/9.5 MB 360.8 kB/s eta 0:00:07
   ----------------------------- ---------- 7.1/9.5 MB 360.8 kB/s eta 0:00:07
   ----------------------------- ---------- 7.1/9.5 MB 360.8 kB/s eta 0:00:07
   ------------------------------ --------- 7.3/9.5 MB 361.5 kB/s eta 0:00:06
   ------------------------------ --------- 7.3/9.5 MB 361.5 kB/s eta 0:00:06
   ------------------------------ --------- 7.3/9.5 MB 361.5 kB/s eta 0:00:06
   -------------------------------- ------- 7.6/9.5 MB 361.7 kB/s eta 0:00:06
   -------------------------------- ------- 7.6/9.5 MB 361.7 kB/s eta 0:00:06
   -------------------------------- ------- 7.6/9.5 MB 361.7 kB/s eta 0:00:06
   --------------------------------- ------ 7.9/9.5 MB 361.4 kB/s eta 0:00:05
   --------------------------------- ------ 7.9/9.5 MB 361.4 kB/s eta 0:00:05
   --------------------------------- ------ 7.9/9.5 MB 361.4 kB/s eta 0:00:05
   --------------------------------- ------ 7.9/9.5 MB 361.4 kB/s eta 0:00:05
   ---------------------------------- ----- 8.1/9.5 MB 360.9 kB/s eta 0:00:04
   ---------------------------------- ----- 8.1/9.5 MB 360.9 kB/s eta 0:00:04
   ---------------------------------- ----- 8.1/9.5 MB 360.9 kB/s eta 0:00:04
   ----------------------------------- ---- 8.4/9.5 MB 361.9 kB/s eta 0:00:04
   ----------------------------------- ---- 8.4/9.5 MB 361.9 kB/s eta 0:00:04
   ----------------------------------- ---- 8.4/9.5 MB 361.9 kB/s eta 0:00:04
   ------------------------------------ --- 8.7/9.5 MB 361.9 kB/s eta 0:00:03
   ------------------------------------ --- 8.7/9.5 MB 361.9 kB/s eta 0:00:03
   ------------------------------------ --- 8.7/9.5 MB 361.9 kB/s eta 0:00:03
   ------------------------------------ --- 8.7/9.5 MB 361.9 kB/s eta 0:00:03
   ------------------------------------- -- 8.9/9.5 MB 362.1 kB/s eta 0:00:02
   ------------------------------------- -- 8.9/9.5 MB 362.1 kB/s eta 0:00:02
   ------------------------------------- -- 8.9/9.5 MB 362.1 kB/s eta 0:00:02
   ------------------------------------- -- 8.9/9.5 MB 362.1 kB/s eta 0:00:02
   ------------------------------------- -- 8.9/9.5 MB 362.1 kB/s eta 0:00:02
   -------------------------------------- - 9.2/9.5 MB 356.1 kB/s eta 0:00:01
   -------------------------------------- - 9.2/9.5 MB 356.1 kB/s eta 0:00:01
   ---------------------------------------  9.4/9.5 MB 359.6 kB/s eta 0:00:01
   ---------------------------------------- 9.5/9.5 MB 359.2 kB/s  0:00:26
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl (232 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.63.0-cp314-cp314-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.3 MB ? eta -:--:--
   -------- ------------------------------- 0.5/2.3 MB 374.6 kB/s eta 0:00:05
   -------- ------------------------------- 0.5/2.3 MB 374.6 kB/s eta 0:00:05
   -------- ------------------------------- 0.5/2.3 MB 374.6 kB/s eta 0:00:05
   ------------- -------------------------- 0.8/2.3 MB 370.4 kB/s eta 0:00:05
   ------------- -------------------------- 0.8/2.3 MB 370.4 kB/s eta 0:00:05
   ------------- -------------------------- 0.8/2.3 MB 370.4 kB/s eta 0:00:05
   ------------- -------------------------- 0.8/2.3 MB 370.4 kB/s eta 0:00:05
   ----------------- ---------------------- 1.0/2.3 MB 368.6 kB/s eta 0:00:04
   ----------------- ---------------------- 1.0/2.3 MB 368.6 kB/s eta 0:00:04
   ----------------- ---------------------- 1.0/2.3 MB 368.6 kB/s eta 0:00:04
   ---------------------- ----------------- 1.3/2.3 MB 369.2 kB/s eta 0:00:03
   ---------------------- ----------------- 1.3/2.3 MB 369.2 kB/s eta 0:00:03
   ---------------------- ----------------- 1.3/2.3 MB 369.2 kB/s eta 0:00:03
   -------------------------- ------------- 1.6/2.3 MB 368.2 kB/s eta 0:00:03
   -------------------------- ------------- 1.6/2.3 MB 368.2 kB/s eta 0:00:03
   -------------------------- ------------- 1.6/2.3 MB 368.2 kB/s eta 0:00:03
   -------------------------- ------------- 1.6/2.3 MB 368.2 kB/s eta 0:00:03
   ------------------------------- -------- 1.8/2.3 MB 366.9 kB/s eta 0:00:02
   ------------------------------- -------- 1.8/2.3 MB 366.9 kB/s eta 0:00:02
   ------------------------------- -------- 1.8/2.3 MB 366.9 kB/s eta 0:00:02
   ----------------------------------- ---- 2.1/2.3 MB 365.8 kB/s eta 0:00:01
   ----------------------------------- ---- 2.1/2.3 MB 365.8 kB/s eta 0:00:01
   ----------------------------------- ---- 2.1/2.3 MB 365.8 kB/s eta 0:00:01
   ---------------------------------------- 2.3/2.3 MB 366.8 kB/s  0:00:06
Downloading kiwisolver-1.5.0-cp314-cp314-win_amd64.whl (75 kB)
Using cached pillow-12.2.0-cp314-cp314-win_amd64.whl (7.2 MB)
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Using cached tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: tzdata, pyparsing, pillow, numpy, kiwisolver, fonttools, cycler, pandas, contourpy, matplotlib, seaborn

   ----------------------------------------  0/11 [tzdata]
   ----------------------------------------  0/11 [tzdata]
   --- ------------------------------------  1/11 [pyparsing]
   --- ------------------------------------  1/11 [pyparsing]
   ------- --------------------------------  2/11 [pillow]
   ------- --------------------------------  2/11 [pillow]
   ------- --------------------------------  2/11 [pillow]
   ------- --------------------------------  2/11 [pillow]
   ------- --------------------------------  2/11 [pillow]
   ------- --------------------------------  2/11 [pillow]
   ------- --------------------------------  2/11 [pillow]
   ------- --------------------------------  2/11 [pillow]
   ------- --------------------------------  2/11 [pillow]
   ------- --------------------------------  2/11 [pillow]
   ------- --------------------------------  2/11 [pillow]
   ------- --------------------------------  2/11 [pillow]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   ---------- -----------------------------  3/11 [numpy]
   -------------- -------------------------  4/11 [kiwisolver]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]
   ------------------ ---------------------  5/11 [fonttools]

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
#  Data Gathering and cleaning........

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [6]:
df = pd.read_csv('movies_metadata.csv')

In [7]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [8]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='str')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  str
 1   belongs_to_collection  4494 non-null   str
 2   budget                 45466 non-null  str
 3   genres                 45466 non-null  str
 4   homepage               7782 non-null   str
 5   id                     45466 non-null  str
 6   imdb_id                45449 non-null  str
 7   original_language      45455 non-null  str
 8   original_title         45466 non-null  str
 9   overview               44512 non-null  str
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  str
 12  production_companies   45463 non-null  str
 13  production_countries   45463 non-null  str
 14  release_date           45379 non-null  str
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  str
 18  status                 45379 non-null  str
 19  tagline                20412 non-null  str
 20  title                  45460 non-null  str
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(2), str(18)
memory usage: 8.3+ MB

In [10]:
df.shape

(45466, 24)

In [11]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [12]:
df = df.drop_duplicates().reset_index(drop=True)

In [13]:
df = df[['title' , 'overview' , 'genres' , 'tagline' , 'vote_average' , 'popularity']]

In [14]:
df = df.dropna(subset=['title'])

In [15]:
df['overview'] = df['overview'].fillna('')

In [16]:
df.iloc[0]['genres']

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [17]:
import ast
df['genres'] = df['genres'].apply(lambda x:" ".join([i['name'] for i in ast.literal_eval(x)]))

In [18]:
df.head()

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519

In [19]:
df['tagline'] = df['tagline'].fillna('')

In [20]:
df['tags'] = df['overview']+ " " + df['genres']+" "+df['tagline']

In [21]:
df.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,Just when George Banks has recovered from his ...

In [22]:
df['tags'][0]

"Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences. Animation Comedy Family "

In [24]:
%pip install nltk

Collecting nltk
  Downloading nltk-3.9.4-py3-none-any.whl.metadata (3.2 kB)
Collecting click (from nltk)
  Using cached click-8.4.1-py3-none-any.whl.metadata (2.6 kB)
Collecting joblib (from nltk)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2026.5.9-cp314-cp314-win_amd64.whl.metadata (41 kB)
Collecting tqdm (from nltk)
  Downloading tqdm-4.68.2-py3-none-any.whl.metadata (58 kB)
Requirement already satisfied: colorama in .\.venv\lib\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.9.4-py3-none-any.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.6 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.6 MB ? eta -:--:--
   ------------- -------------------------- 0.5/1.6 MB 569.6 kB/s eta 0:00:02
   ------------- -------------------------- 0.5/1.6 MB 569.6 kB/s eta 0:00:02
   ------------- -------------------------- 0.5/1.6 MB 569.6 kB/s eta 0:00:02
   ------------- -------------------------- 0.5/1.6 MB 569.6 kB/s eta 0:00:02
   -------------------- ------------------- 0.8/1.6 MB 439.7 kB/s eta 0:00:02
   -------------------- ------------------- 0.8/1.6 MB 439.7 kB/s eta 0:00:02
   -------------------- ------------------- 0.8/1.6 MB 439.7 kB/s eta 0:00:02
   --------------------------- ------------ 1.0/1.6 MB 402.7 kB/s eta 0:00:02
   --------------------------- ------------ 1.0/1.6 MB 402.7 kB/s eta 0:00:02
   --------------------------- ------------ 1.0/1.6 MB 402.7 kB/s eta 0:00:02
   --------------------------------- ------ 1.3/1.6 MB 393.2 kB/s eta 0:00:01
   --------------------------------- ------ 1.3/1.6 MB 393.2 kB/s eta 0:00:01
   --------------------------------- ------ 1.3/1.6 MB 393.2 kB/s eta 0:00:01
   --------------------------------- ------ 1.3/1.6 MB 393.2 kB/s eta 0:00:01
   ---------------------------------------- 1.6/1.6 MB 382.9 kB/s  0:00:04
Downloading regex-2026.5.9-cp314-cp314-win_amd64.whl (280 kB)
Using cached click-8.4.1-py3-none-any.whl (116 kB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading tqdm-4.68.2-py3-none-any.whl (78 kB)
Installing collected packages: tqdm, regex, joblib, click, nltk

   ---------------------------------------- 0/5 [tqdm]
   ---------------------------------------- 0/5 [tqdm]
   ---------------------------------------- 0/5 [tqdm]
   -------- ------------------------------- 1/5 [regex]
   -------- ------------------------------- 1/5 [regex]
   ---------------- ----------------------- 2/5 [joblib]
   ---------------- ----------------------- 2/5 [joblib]
   ---------------- ----------------------- 2/5 [joblib]
   ---------------- ----------------------- 2/5 [joblib]
   ---------------- ----------------------- 2/5 [joblib]
   ---------------- ----------------------- 2/5 [joblib]
   ---------------- ----------------------- 2/5 [joblib]
   ---------------- ----------------------- 2/5 [joblib]
   ---------------- ----------------------- 2/5 [joblib]
   ------------------------ --------------- 3/5 [click]
   ------------------------ --------------- 3/5 [click]
   ------------------------ --------------- 3/5 [click]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   -------------------------------- ------- 4/5 [nltk]
   ---------------------------------------- 5/5 [nltk]

Successfully installed click-8.4.1 joblib-1.5.3 nltk-3.9.4 regex-2026.5.9 tqdm-4.68.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [26]:
#  NLP Text preprocessing.......

import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [27]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Prottay\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Prottay\AppData\Roaming\nltk_data...

True

In [28]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [29]:
def preprocess_text(text):
  text = str(text).lower()
  text= re.sub(r'[^a-zA-Z\s]', '', text)

  words = text.split()
  words=[word for word in words if  word not in stop_words]

  words=[lemmatizer.lemmatize(word)for word in words]
  return " ".join(words)

In [30]:
df['tags'] = df['tags'].apply(preprocess_text)

In [31]:
df['tags'][1]

'sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult who trapped inside game year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creature adventure fantasy family roll dice unleash excitement'

In [32]:
# Text Vectorization......

df = df.reset_index(drop = True)

In [33]:
indices = pd.Series(df.index,index = df['title']).drop_duplicates()
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45442
Century of Birthing            45443
Betrayal                       45444
Satan Triumphant               45445
Queerama                       45446
Length: 45447, dtype: int64

In [35]:
%pip install scikit-learn

Collecting scikit-learn
  Using cached scikit_learn-1.9.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in .\.venv\lib\site-packages (from scikit-learn) (2.4.6)
Collecting scipy>=1.10.0 (from scikit-learn)
  Using cached scipy-1.17.1-cp314-cp314-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: joblib>=1.4.0 in .\.venv\lib\site-packages (from scikit-learn) (1.5.3)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Using cached narwhals-2.22.1-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.9.0-cp314-cp314-win_amd64.whl (8.3 MB)
Using cached narwhals-2.22.1-py3-none-any.whl (454 kB)
Using cached scipy-1.17.1-cp314-cp314-win_amd64.whl (37.3 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, scikit-learn

   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   -------------------- ------------------- 2/4 [narwhals]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ---------------------------------------- 4/4 [scikit-learn]

Successfully installed narwhals-2.22.1 scikit-learn-1.9.0 scipy-1.17.1 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [37]:
tfidf = TfidfVectorizer(max_features=5000,ngram_range=(1,2),
stop_words='english')

In [38]:
tfidf_matrix = tfidf.fit_transform(df['tags'])

In [39]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1117947 stored elements and shape (45447, 5000)>

In [40]:
# Cosine_Similarity .......

from sklearn.metrics.pairwise import cosine_similarity

In [41]:
def recommend(title, n=10):
  if title not in indices:
    return ['Movie not found']

  idx = indices[title]
  sim_score = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
  similar_idx = sim_score.argsort()[::-1][1:n+1]
  return df['title'].iloc[similar_idx]

In [42]:
recommend('Toy Story')

28972                    Superstar Goofy
45117                             Banana
2996                         Toy Story 2
44159                  Botsman i Popugay
21919               Toy Story of Terror!
25786                    Partysaurus Rex
24510                  Hawaiian Vacation
31493                          Bar Sport
37282    Father of Four: Never Gives Up!
45063                      Tatu and Patu
Name: title, dtype: str

In [43]:
import pickle
pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb'))
pickle.dump(indices,open('indices.pkl','wb'))
df.to_pickle('df.pkl')
pickle.dump(tfidf,open('tfidf.pkl','wb'))